name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-nginx-app .

    - name: Save Docker image as artifact
      run: docker save my-nginx-app -o my-nginx-app.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-docker-artifact
        path: my-nginx-app.tar
